name: flutter_jan_2020
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dots_indicator: ^1.1.0
  scrollable_bottom_sheet: ^0.2.1
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/0101/image.jpg
    - assets/0101/image1.png
    - assets/0101/image2.png
    - assets/0102/guitar.png
    - assets/0107/image.png
    - assets/0109/image.png
    - assets/0109/image1.png
    - assets/0109/image2.png
    - assets/0109/image3.png
    - assets/0109/image10.png
    - assets/0109/image11.png
    - assets/0109/image12.png
    - assets/0109/image13.png
    - assets/0110/image.jpg
    - assets/0110/image1.jpg
    - assets/0110/image2.jpg
    - assets/0110/image3.jfif
    - assets/0110/image10.jpg
    - assets/0110/image11.jpg
    - assets/0110/image12.jpg
    - assets/0110/image13.jpeg
    - assets/0112/image.png